sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t tijanasutara/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tijanasutara/react-test npm run test -- --coverage

after_success:
  - docker build -t tijanasutara/multi-client ./client
  - docker build -t tijanasutara/multi-nginx ./nginx
  - docker build -t tijanasutara/multi-server ./server
  - docker build -t tijanasutara/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tijanasutara/multi-client
  - docker push tijanasutara/multi-nginx
  - docker push tijanasutara/multi-server
  - docker push tijanasutara/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-274155267504'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY